# Generated by Django 3.2.8 on 2023-06-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='营期')),
                ('start', models.DateField(verbose_name='开始日期')),
                ('end', models.DateField(verbose_name='结束日期')),
                ('total_people', models.IntegerField(verbose_name='总人数')),
                ('remainder', models.IntegerField(verbose_name='剩余人数')),
                ('symbol', models.IntegerField(verbose_name='第几期')),
            ],
            options={
                'db_table': 'c_camp',
            },
        ),
        migrations.CreateModel(
            name='JCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='营期')),
                ('start', models.DateField(verbose_name='开始日期')),
                ('end', models.DateField(verbose_name='结束日期')),
                ('total_people', models.IntegerField(verbose_name='总人数')),
                ('remainder', models.IntegerField(verbose_name='剩余人数')),
                ('symbol', models.IntegerField(verbose_name='第几期')),
            ],
            options={
                'db_table': 'j_camp',
            },
        ),
        migrations.CreateModel(
            name='TenatCampPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_camp', models.CharField(blank=True, max_length=10, null=True, verbose_name='畅享营价格')),
                ('j_camp', models.CharField(blank=True, max_length=10, null=True, verbose_name='畅享营价格')),
                ('tenat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenat.tenat')),
            ],
            options={
                'db_table': 'tenat_camp_price',
            },
        ),
    ]
