# Generated by Django 3.2.8 on 2023-06-26 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 7, 20, 52, 242867))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 7, 20, 52, 242888))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
