# Generated by Django 3.2.8 on 2023-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('qrcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='二维码')),
                ('paycode', models.CharField(blank=True, max_length=50, null=True, verbose_name='二维码')),
            ],
            options={
                'db_table': 'tenat',
            },
        ),
    ]
